name: Deploy AI Artistic Style Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Pull Docker Image
        run: docker pull urmsandeep/ai-artistic-style-service:latest
      - name: Deploy Service
        run: |
          docker-compose down
          docker-compose up -d
